package com.line.linebot.model;

public class LineUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LINE_USER.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LINE_USER.LINE_TOKEN
     *
     * @mbg.generated
     */
    private String user_line_token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LINE_USER.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LINE_USER.DEPT_CODE
     *
     * @mbg.generated
     */
    private String dept_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LINE_USER.TEAM_CODE
     *
     * @mbg.generated
     */
    private String team_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LINE_USER.USER_STATUS
     *
     * @mbg.generated
     */
    private String user_status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LINE_USER.MEMO
     *
     * @mbg.generated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LINE_USER.ID
     *
     * @return the value of LINE_USER.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LINE_USER.ID
     *
     * @param id the value for LINE_USER.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LINE_USER.LINE_TOKEN
     *
     * @return the value of LINE_USER.LINE_TOKEN
     *
     * @mbg.generated
     */
    public String getUser_line_token() {
        return user_line_token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LINE_USER.LINE_TOKEN
     *
     * @param user_line_token the value for LINE_USER.LINE_TOKEN
     *
     * @mbg.generated
     */
    public void setUser_line_token(String user_line_token) {
        this.user_line_token = user_line_token == null ? null : user_line_token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LINE_USER.NAME
     *
     * @return the value of LINE_USER.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LINE_USER.NAME
     *
     * @param name the value for LINE_USER.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LINE_USER.DEPT_CODE
     *
     * @return the value of LINE_USER.DEPT_CODE
     *
     * @mbg.generated
     */
    public String getDept_code() {
        return dept_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LINE_USER.DEPT_CODE
     *
     * @param dept_code the value for LINE_USER.DEPT_CODE
     *
     * @mbg.generated
     */
    public void setDept_code(String dept_code) {
        this.dept_code = dept_code == null ? null : dept_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LINE_USER.TEAM_CODE
     *
     * @return the value of LINE_USER.TEAM_CODE
     *
     * @mbg.generated
     */
    public String getTeam_code() {
        return team_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LINE_USER.TEAM_CODE
     *
     * @param team_code the value for LINE_USER.TEAM_CODE
     *
     * @mbg.generated
     */
    public void setTeam_code(String team_code) {
        this.team_code = team_code == null ? null : team_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LINE_USER.USER_STATUS
     *
     * @return the value of LINE_USER.USER_STATUS
     *
     * @mbg.generated
     */
    public String getUser_status() {
        return user_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LINE_USER.USER_STATUS
     *
     * @param user_status the value for LINE_USER.USER_STATUS
     *
     * @mbg.generated
     */
    public void setUser_status(String user_status) {
        this.user_status = user_status == null ? null : user_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LINE_USER.MEMO
     *
     * @return the value of LINE_USER.MEMO
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LINE_USER.MEMO
     *
     * @param memo the value for LINE_USER.MEMO
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}